version: '3.6'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports: ['9200:9200']
    networks:
      - esnet
  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.4
    container_name: kibana
    ports: ['5601:5601']
    depends_on: ['elasticsearch']
    networks:
      - esnet
  fluentd:
    build: ./fluentd-elasticsearch
    ports: ["24224:24224"]
    depends_on: ['elasticsearch']    
    networks:
      - esnet
networks:
  esnet:
    name: elasticsearch
    driver: bridge
